services:
  etl-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - AEMET_API_KEY=${AEMET_API_KEY}
      - PROJECT_ID=${PROJECT_ID}
      - PORT=8000
